headers = {
    'authority': 'www.instagram.com',
    'accept': '*/*',
    'accept-language': 'en-US,en;q=0.9',
    'content-type': 'application/x-www-form-urlencoded',
    'cookie': 'csrftoken=cawbTDUrFhQwHqeV6ELge0o8WkylCxJq; mid=ZTjPCwALAAFWUWnoHIdWLwOT4noG; ig_did=FAAE49B4-179D-49ED-A630-E68B0FCC3947; ig_nrcb=1; datr=Cs84ZarQmRvh-8wX-DBJUDhx',
    'dnt': '1',
    'dpr': '1',
    'origin': 'https://www.instagram.com',
    'sec-ch-prefers-color-scheme': 'light',
    'sec-ch-ua': '"Chromium";v="118", "Google Chrome";v="118", "Not=A?Brand";v="99"',
    'sec-ch-ua-full-version-list': '"Chromium";v="118.0.5993.89", "Google Chrome";v="118.0.5993.89", "Not=A?Brand";v="99.0.0.0"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-model': '""',
    'sec-ch-ua-platform': 'Windows',
    'sec-ch-ua-platform-version': '10.0.0',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36',
    'viewport-width': '517',
    'x-asbd-id': '129477',
    'x-csrftoken': 'cawbTDUrFhQwHqeV6ELge0o8WkylCxJq',
    'x-fb-friendly-name': 'PolarisPostActionLoadPostQueryQuery',
    'x-fb-lsd': 'AVpKq9If6G0',
    'x-ig-app-id': '936619743392459',
}
